version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/webvalue
      - JWT_SECRET=your_jwt_secret_here
      - SENDGRID_API_KEY=your_sendgrid_key
      - GOOGLE_CLIENT_ID=your_google_client_id
      - GOOGLE_CLIENT_SECRET=your_google_client_secret
      - MICROSOFT_CLIENT_ID=your_microsoft_client_id
      - MICROSOFT_CLIENT_SECRET=your_microsoft_client_secret
    depends_on:
      - db
    networks:
      - app-network
    volumes:
      - ./backend/logs:/usr/src/app/logs

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "80:80"
    environment:
      - REACT_APP_API_URL=http://backend:5000/api
      - REACT_APP_VAPID_PUBLIC_KEY=your_vapid_key
    depends_on:
      - backend
    networks:
      - app-network

  db:
    image: postgres:14-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=webvalue
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network
    ports:
      - "5432:5432"

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data:
